workflows:
  android-workflow:
    name: Android Build
    environment:
      java: 17
    scripts:
      - name: Extract Project and Build
        script: |
          unzip -o "ai boray.zip"
          
          GRADLEW_DIR=$(find . -name "build.gradle.kts" -exec dirname {} \; | head -n 1)
          if [ -n "$GRADLEW_DIR" ]; then
            cd "$GRADLEW_DIR"
          fi
          
          # البناء مع تخطي أخطاء التحقق ومطابقة المكتبات الخارجية إجبارياً
          gradle assembleDebug --no-daemon -x test -x check
    artifacts:
      - "**/build/outputs/**/*.apk"
